name: Check code with eslint and mocha test

on:
  pull_request:
    branches: [develop]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
      - name: Check
        run:
          npm ci
          npm run lint-diff
        env:
          CI: true
          BASE: ${{github.base_ref}}
          HEAD: ${{github.head_ref}}